version: "0.1"
user: vishnuknair
key: '********'
testSuites: []
pre: [rm -rf node_modules, npm install, npx playwright install, npx playwright install-deps]
preDirectives:
    commands: [rm -rf node_modules, npm install, npx playwright install, npx playwright install-deps]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
post: [rm -f demo.txt]
postDirectives:
    commands: [rm -f demo.txt]
    shell: ""
    workingDirectory: ""
env:
    LT_ACCESS_KEY: LT_mu5SYdU4hWfecLZm7vn5zOWOV7WW720LcdOnV9Eknq3ctYj
    LT_USERNAME: vishnuknair
    executeOn: local
runson: linux
autosplit: true
concurrency: 1
testDiscovery:
    autosubset: true
    command: find tests -name "test_*.spec.js" -type f
    mode: dynamic
    type: raw
testRunnerCommand: npm run testHE -- $test
tunnelOpts:
    testsPerTunnel: 10
retryOnFailure: true
maxRetries: 3
jobID: 1fa515ec-26ec-4fa9-b47c-438be787a400
codeDirectory: playwright-test-js
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: ""
        testSuitePath: ""
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices: []
        deviceSelectionStrategy: ""
        appId: ""
        testSuiteAppId: ""
        xcTestPlanId: ""
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: null
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        minorOsVersion: false
        playwrightRD: false
        mobileDC: null
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
        mitmProxy: false
        localhost: false
        networkHar: false
        artifacts: false
        otherApps: []
        customData: {}
        smartUI: null
        darkMode: false
        testRemarks: false
        autoGrantPermissions: false
        networkLogsOptions:
            captureContent: false
            excludeHosts: []
            includeHosts: []
        enableResultBundle: false
        enableBluetooth: false
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
testType: playwright
triggerSource: CLI
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: null
platformConfig: null
differentialUpload:
    enabled: false
    ttlHours: null
    forcedDisabled: false
project:
    id: 01JZ03GE64ZZA2HBVGCPBNJ4FF
    name: LambdaTest Default Project
    type: custom
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
testDiscoveryResultV3: []
storageType: ""
localHTTPProxy: ""
regionConfig:
    vm: []
    storage:
        region: ""
        enabled: false
        name: ""
        platform: azure
waitForArtefactsUpload: false
unzipPayload: false
projectpath: ""
accessibilityJob: false
globalPre:
    mode: ""
    commands: []
    maxRetries: 0
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
    yamlPath: null
    type: ""
    location: ""
globalPost:
    mode: ""
    commands: []
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
    downloadArtifacts: false
    email:
        to: []
        metaInfo: []
        linkValidity: 0
        templatePath: ""
    disableEmail: false
slackChannel: ""
whiteLabelProductTag: ""
sprofilePath: ""
ltOptions: {}
onpremEnv: ""
